const express = require('express');
const { PythonShell } = require('python-shell');

const router = express.Router();

router.post('/summarize', (req, res) => {
    const text = req.body.text; // Get the text from the request

  const options = {
    scriptPath: '..',
    args: [text],
  };

  PythonShell.run('Summarize.py', options, (err, results) => {
    if (err) {
      console.error(err);
      res.status(500).json({ error: 'An error occurred' });
    } else {
      const summary = results[0]; // The summary generated by your Python script
      res.json({ summary });
    }
  });
});

module.exports = router;
